[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ctt2md"
version = "0.1.0"
description = "Convert math PDF textbooks to Markdown using Qwen 3 VL via OpenAI"
readme = "README.md"
authors = [{ name = "Lortzing" }]
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
    "pdf2image>=1.17",
    "pillow>=10.0",
    "openai>=1.30",
    "python-dotenv>=1.0",
    "tqdm>=4.66"
]

[project.scripts]
ctt2md = "ctt2md.cli:main"
